import shortid from "shortid";
import { FaHome,FaUser } from "react-icons/fa"
import { MdOutlineAddCircle } from "react-icons/md";
import { TbBrandBooking } from "react-icons/tb";
import { MdDashboard } from "react-icons/md";

export const navbar = [
    {
        name:"Home",
        url:'/',
        icon:''
    },
    {
        name:'Transport',
        url:'/',
        icon:''
    },  
    {
        name:'Dashboard',
        url:'/admin/dashboard',
        icon:''
    }
]

export const adminNavbar = [
    {
        name:'Back To Home',
        icon:FaHome,
        url:'/'
    },
    {
        name:'Dashboard',
        icon:MdDashboard,
        url:'/admin/dashboard'
    },
    {
        name:'Add Bus',
        icon:MdOutlineAddCircle,
        url:'/admin/addbus'
    },
    {
        name:'All User',
        icon:FaUser,
        url:'/admin/alluser'
    },
    {
        name:'Bookings',
        icon:TbBrandBooking,
        url:'/admin/booking'
    },

]

export const oneByOneSeat = [
    {
        seatName:'A1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'A2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'A3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'J1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'J2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'J3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    }
]

export const twoByTwoSeat = [
    {
        seatName:'A1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'A2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'A3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'A4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'B4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'C4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'D4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'E4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'F4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'G4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'H4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I1',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I2',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I3',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
    {
        seatName:'I4',
        seatId:shortid.generate(),
        isBooked:false,
        bookingUser:{}
    },
   
]